### ISSUE TITLE
Adjust data step to deal with multiple polls in a day

### ISSUE THREAD

**Issue by johnwoodill** [johnwoodill/2020-battleground-forecasting#1]
We need to make some decisions around handling multiple polls in a day, such as:
* Average each day for each candidate in each state
* Weighted average of poll quality for each day in each day

**Comment by ghost** [comment]
I wonder if we don't want to treat the "true" poll value as a parameter in the model.  Essentially this treats it as a missing value and imputes it during model fitting, based on the weighted average you suggest.  

Kinda interesting to see two poll snapshots on the same day to show uncertainty.  For instance, our 100 sampled GPs should be able to capture both polls.  We could also use the SD of simultaneous polls to inform the prior on the sigma.

Sorry this is a stream of thought but maybe we could go with your weighted average and use the SD of simultaneous polls to inform the sigma prior.

**Comment by ghost** [comment]
FYI. Here's how pkremp did it in the gelman post.  Check out line 135.

https://github.com/pkremp/polls/blob/master/runmodel.R 

He just drops overlapping polls by keeping most recent.  I think it's better what we're doing.
